# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    base_path: "assets/fosckeditor"
    js_path:   "assets/fosckeditor/ckeditor.js"
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Youtube', 'Iframe', '-', 'Table', '-', 'Format', '-', 'Source'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins: "youtube"
            allowedContent: true
            language: "fr"
    plugins:
        youtube:
            path: "assets/fosckeditor/plugins/youtube/" # with trailing slash
            filename: "plugin.js"