# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    base_path: "assets/plugins/ckeditor"
    js_path:   "assets/plugins/ckeditor/ckeditor.js"
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Youtube', '-', 'Table', '-', 'Format', '-', 'Source', 'Markdown'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins: ['youtube', 'markdown', 'lazyload']
            allowedContent: ['img(*)[*]', 'p[id]', 'h2[id]', 'h3[id]', 'strong', 'a[!href, target, rel]', 'ol', 'ul[id]', 'li[id]', 'i', 'blockquote', 'pre', 'code', 'div(*)[*]', 'table', 'tr', 'td', 'tbody']
            fillEmptyBlocks: false
            language: "fr"
            entities: false
            basicEntities: false
    plugins:
        youtube:
            path: "assets/plugins/ckeditor/plugins/youtube/" # with trailing slash
            filename: "plugin.js"
        markdown:
            path: "assets/plugins/ckeditor/plugins/markdown/"
            filename: "plugin.js"
        lazyload:
            path: "assets/plugins/ckeditor/plugins/lazyload/"
            filename: "plugin.js"