# See the configuration reference at https://github.com/scheb/2fa/blob/master/doc/configuration.md
scheb_two_factor:
    backup_codes:
        enabled: false
    google:
        enabled: true
        server_name: Le Monde Du PC       # Server name used in QR code
        issuer: Le Monde Du PC            # Issuer name used in QR code
        digits: 6                      # Number of digits in authentication code
        window: 1                      # How many codes before/after the current one would be accepted as valid
        template: user/2fa.html.twig   # Template used to render the authentication form
    security_tokens:
#        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        # If you're using guard-based authentication, you have to use this one:
         - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
        # If you're using authenticator-based security (introduced in Symfony 5.1), you have to use this one:
#         - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
