<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\BlogController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/BlogController.php';

$this->services['App\\Controller\\BlogController'] = $instance = new \App\Controller\BlogController(($this->privates['App\\Repository\\PostsRepository'] ?? $this->load('getPostsRepositoryService.php')), ($this->privates['App\\Repository\\UsersRepository'] ?? $this->load('getUsersRepositoryService.php')), ($this->privates['App\\Repository\\InteractionsRepository'] ?? $this->load('getInteractionsRepositoryService.php')), ($this->privates['App\\Repository\\TagsRepository'] ?? $this->load('getTagsRepositoryService.php')));

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('App\\Controller\\BlogController', $this));

return $instance;
