<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'easyadmin.form.guesser.missing_doctrine_orm_type_guesser' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeGuesserInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/doctrine-bridge/Form/DoctrineOrmTypeGuesser.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Form/Guesser/MissingDoctrineOrmTypeGuesser.php';

return $this->services['easyadmin.form.guesser.missing_doctrine_orm_type_guesser'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Guesser\MissingDoctrineOrmTypeGuesser(($this->services['doctrine'] ?? $this->getDoctrineService()));
