<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOx2ZmAf\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOx2ZmAf/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOx2ZmAf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOx2ZmAf\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerOx2ZmAf\srcApp_KernelProdContainer([
    'container.build_hash' => 'Ox2ZmAf',
    'container.build_id' => 'fa79d9bf',
    'container.build_time' => 1551392027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOx2ZmAf');
