# routes to match with the old version
product:
  path: /article/{id}/{slug}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: product_show
    permanent: true
    keepQueryParams: true

about:
  path: /divers/a-propos
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: page_about
    permanent: true

contact:
  path: /divers/contact
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: page_contact
    permanent: true