<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.container_repository_factory' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/RepositoryFactory.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php';

return $this->privates['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Repository\\InteractionsRepository' => ['privates', 'App\\Repository\\InteractionsRepository', 'getInteractionsRepositoryService.php', true],
    'App\\Repository\\PartnersRepository' => ['privates', 'App\\Repository\\PartnersRepository', 'getPartnersRepositoryService.php', true],
    'App\\Repository\\PostsRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService.php', true],
    'App\\Repository\\TagsRepository' => ['privates', 'App\\Repository\\TagsRepository', 'getTagsRepositoryService.php', true],
    'App\\Repository\\UsersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService.php', true],
]));
