<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translation.dumper.php' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/DumperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/FileDumper.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Dumper/PhpFileDumper.php';

return $this->privates['translation.dumper.php'] = new \Symfony\Component\Translation\Dumper\PhpFileDumper();
