<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.template_iterator' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/twig-bundle/TemplateIterator.php';

return $this->privates['twig.template_iterator'] = new \Symfony\Bundle\TwigBundle\TemplateIterator(($this->services['kernel'] ?? $this->get('kernel', 1)), ($this->targetDirs[3].'/src'), [($this->targetDirs[3].'/vendor/symfony/twig-bridge/Resources/views/Form') => NULL], ($this->targetDirs[3].'/templates'));
