<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.choice_list_factory.property_access' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/ChoiceList/Factory/ChoiceListFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ChoiceList/Factory/PropertyAccessDecorator.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ChoiceList/Factory/DefaultChoiceListFactory.php';

return $this->privates['form.choice_list_factory.property_access'] = new \Symfony\Component\Form\ChoiceList\Factory\PropertyAccessDecorator(($this->privates['form.choice_list_factory.default'] ?? ($this->privates['form.choice_list_factory.default'] = new \Symfony\Component\Form\ChoiceList\Factory\DefaultChoiceListFactory())), ($this->privates['property_accessor'] ?? $this->load('getPropertyAccessorService.php')));
