<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.csrf.token_generator' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-csrf/TokenGenerator/TokenGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-csrf/TokenGenerator/UriSafeTokenGenerator.php';

return $this->privates['security.csrf.token_generator'] = new \Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator();
