<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQMxnSUo\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQMxnSUo/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQMxnSUo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQMxnSUo\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerQMxnSUo\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'QMxnSUo',
    'container.build_id' => '079c6264',
    'container.build_time' => 1551392081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQMxnSUo');
