<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX92EHAq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX92EHAq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX92EHAq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX92EHAq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX92EHAq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X92EHAq',
    'container.build_id' => 'c7ef63fc',
    'container.build_time' => 1558277484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX92EHAq');
