<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQZe09vK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQZe09vK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQZe09vK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQZe09vK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQZe09vK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QZe09vK',
    'container.build_id' => 'c8984043',
    'container.build_time' => 1558276950,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQZe09vK');
