<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1ZUxfCx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1ZUxfCx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1ZUxfCx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1ZUxfCx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1ZUxfCx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1ZUxfCx',
    'container.build_id' => '3206898d',
    'container.build_time' => 1551436499,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1ZUxfCx');
